//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApisBurguer
{
    using System;
    using System.Collections.Generic;
    
    public partial class listaComidas
    {
        public int idComida { get; set; }
        public string nombreComida { get; set; }
        public string descripcionComida { get; set; }
        public int precioComida { get; set; }
        public string imagenComida { get; set; }
    }
}
