//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApisBurguer
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocionesContratadas
    {
        public int idPromocionContratada { get; set; }
        public int idPromocion { get; set; }
        public string nombreCliente { get; set; }
        public string apellidoCliente { get; set; }
        public string telefonoCliente { get; set; }
        public string direccionCliente { get; set; }
        public string fechaPedido { get; set; }
        public string fechaEntrega { get; set; }
    
        public virtual promociones promociones { get; set; }
    }
}
