//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApisBurguer
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        public int idProveedor { get; set; }
        public string nombreProveedor { get; set; }
        public string domicilioProveedor { get; set; }
        public string telefonoProveedor { get; set; }
    }
}
